version: '3'
services:
  client.webmanza.com.3001:
    image: client.webmanza.com
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    env_file: .env
    container_name: client.webmanza.com.3001
    restart: unless-stopped
  client.webmanza.com.3002:
    image: client.webmanza.com
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3002:3001'
    env_file: .env
    container_name: client.webmanza.com.3002
    restart: unless-stopped
